version: "3"
services:
  app:
    tty: true
    container_name: app
    build:
      context: ./docker/app/
      #dockerfile:: ./docker/app/Dockerfile
    volumes:
      - ./data/app/aws:/root/.aws
    